---
title: Never log in to your servers again with Ansible
theme: metropolis
output:
  beamer_presentation:
    theme: metropolis
---
`r source("config.R")`

# Origins of the name "ansible"

```{r enders-game-cover}
draw_image("img/enders-game-cover.jpg")
```

# Use Ansible to orchestrate server operations

```{r ansible-orchestra, engine="dot"}
digraph {
  fontname=Helvetica;
  node[fontname=Helvetica shape=circle style=filled];
  control -> {web1, web2, web3, db1, db2};
  control[fillcolor="#fc8d62"];
  web1, web2, web3[fillcolor="#66c2a5"];
  db1, db2[fillcolor="#8da0cb"];
}
```

# Control a single server with Ansible

```{r ansible-simple, engine="dot"}
digraph {
  fontname=Helvetica;
  node[fontname=Helvetica shape=circle style=filled];
  laptop -> server;
  laptop[fillcolor="#fc8d62"];
  server[fillcolor="#66c2a5"];
}
```

# Share control of servers

```{r ansible-tower, engine="dot"}
digraph {
  fontname=Helvetica;
  node[fontname=Helvetica shape=circle style=filled];
  {player1, player2, player3} -> control -> {web1, web2, web3, db1, db2};
  player1, player2, player3[fillcolor="#e78ac3"];
  control[fillcolor="#fc8d62"];
  web1, web2, web3[fillcolor="#66c2a5"];
  db1, db2[fillcolor="#8da0cb"];
}
```

# Ansible for DevOps

```{r ansible-for-devops}
grid.arrange(
  read_image("img/ansible-for-devops-cover.jpg"),
  read_image("img/jeff-geerling.jpg"),
  nrow = 1,
  widths = c(0.6, 0.4)
)
```

# Command line tools

ansible
:   Run an ad-hoc command.

playbook
:   Run a playbook.

vault
:   Simple encryption.

galaxy
:   Use/develop 3rd party modules.

# Vocabulary

playbook
:   YAML file containing one or more plays.

play
:   A play is a collection of tasks run on a host or hosts.

task
:   A task is a single unit of labor.

module
:   A module is command or command wrapper.

# Vocabulary (continued)

inventory
:   A description of IP addresses and names.

role
:   A bundle of tasks and variables to accomplish some modular goal.

idempotent
:   Design philosophy underlying Ansible. Only change things when needed.
